export const ADD_BURGARELEMENT = "ADD_BURGARELEMENT";
export const REMOVE_BURGARELEMENT = "REMOVE_BURGARELEMENT";
export const UPDATE_PURCHASABLE = "UPDATE_PURCHASABLE";

export const RESET_BURGARELEMENT = "RESET_BURGARELEMENT";

export const LOAD_ORDERS = "LOAD_ORDERS";
export const ORDERS_LOAD_FAIELD = "ORDERS_LOAD_FAIELD";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIELD = "AUTH_FAIELD";
export const AUTH_LODDING = "AUTH_LODDING";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
